---
# Main Ansible playbook for testing the PyLama ecosystem

- name: PyLama Ecosystem Tests
  hosts: local
  gather_facts: yes
  vars:
    bexy_url: "{{ lookup('env', 'BEXY_URL') | default('http://localhost:8001', true) }}"
    getllm_url: "{{ lookup('env', 'GETLLM_URL') | default('http://localhost:8002', true) }}"
    apilama_url: "{{ lookup('env', 'APILAMA_URL') | default('http://localhost:8080', true) }}"
    weblama_url: "{{ lookup('env', 'WEBLAMA_URL') | default('http://localhost:8081', true) }}"
    devlama_url: "{{ lookup('env', 'DEVLAMA_URL') | default('http://localhost:5000', true) }}"
    test_output_dir: "{{ playbook_dir }}/../test-reports"
    cleanup_enabled: "{{ lookup('env', 'CLEANUP_ENABLED') | default('true', true) }}"
    generate_report: "{{ lookup('env', 'GENERATE_REPORT') | default('true', true) }}"
  
  tasks:
    - name: Create test output directory
      file:
        path: "{{ test_output_dir }}"
        state: directory
        mode: '0755'
      
    - name: Check BEXY health
      uri:
        url: "{{ bexy_url }}/health"
        method: GET
        status_code: 200
      register: bexy_health
      ignore_errors: yes
      
    - name: Check PyLLM health
      uri:
        url: "{{ getllm_url }}/health"
        method: GET
        status_code: 200
      register: getllm_health
      ignore_errors: yes
      
    - name: Check APILama health
      uri:
        url: "{{ apilama_url }}/health"
        method: GET
        status_code: 200
      register: apilama_health
      ignore_errors: yes
      
    - name: Check WebLama health
      uri:
        url: "{{ weblama_url }}/health"
        method: GET
        status_code: 200
      register: weblama_health
      ignore_errors: yes
      
    - name: Check PyLama health
      uri:
        url: "{{ devlama_url }}/health"
        method: GET
        status_code: 200
      register: devlama_health
      ignore_errors: yes
      
    - name: Display service health status
      debug:
        msg: |
          BEXY: {{ 'OK' if bexy_health.status == 200 else 'FAIL' }}
          PyLLM: {{ 'OK' if getllm_health.status == 200 else 'FAIL' }}
          APILama: {{ 'OK' if apilama_health.status == 200 else 'FAIL' }}
          WebLama: {{ 'OK' if weblama_health.status == 200 else 'FAIL' }}
          PyLama: {{ 'OK' if devlama_health.status == 200 else 'FAIL' }}

# Include component-specific test playbooks
- import_playbook: playbooks/bexy_tests.yml
- import_playbook: playbooks/getllm_tests.yml
- import_playbook: playbooks/apilama_tests.yml
- import_playbook: playbooks/weblama_tests.yml
- import_playbook: playbooks/integration_tests.yml

# Generate test report
- name: Generate Test Report
  hosts: local
  gather_facts: no
  vars:
    test_output_dir: "{{ playbook_dir }}/../test-reports"
    generate_report: "{{ lookup('env', 'GENERATE_REPORT') | default('true', true) }}"
  
  tasks:
    - name: Generate HTML test report
      template:
        src: templates/report_template.html.j2
        dest: "{{ test_output_dir }}/test_report.html"
      when: generate_report | bool
      
    - name: Display report location
      debug:
        msg: "Test report generated at {{ test_output_dir }}/test_report.html"
      when: generate_report | bool
