---
# Integration tests for the PyLama ecosystem

- name: PyLama Ecosystem Integration Tests
  hosts: local
  gather_facts: no
  vars:
    pybox_url: "{{ lookup('env', 'PYBOX_URL') | default('http://localhost:8001', true) }}"
    pyllm_url: "{{ lookup('env', 'PYLLM_URL') | default('http://localhost:8002', true) }}"
    apilama_url: "{{ lookup('env', 'APILAMA_URL') | default('http://localhost:8080', true) }}"
    weblama_url: "{{ lookup('env', 'WEBLAMA_URL') | default('http://localhost:8081', true) }}"
    pylama_url: "{{ lookup('env', 'PYLAMA_URL') | default('http://localhost:5000', true) }}"
    test_output_dir: "{{ playbook_dir }}/../test-reports"
  
  tasks:
    - name: Test APILama to PyBox integration
      uri:
        url: "{{ apilama_url }}/api/execute"
        method: POST
        body_format: json
        body:
          code: "print('Testing APILama to PyBox integration')"
          language: "python"
        status_code: 200
      register: apilama_pybox_result
      
    - name: Verify APILama to PyBox integration
      assert:
        that:
          - apilama_pybox_result.status == 200
          - apilama_pybox_result.json.output is defined
          - "'Testing APILama to PyBox integration' in apilama_pybox_result.json.output"
        fail_msg: "APILama to PyBox integration failed"
        success_msg: "APILama to PyBox integration successful"
      
    - name: Test APILama to PyLLM integration
      uri:
        url: "{{ apilama_url }}/api/complete"
        method: POST
        body_format: json
        body:
          prompt: "Testing APILama to PyLLM integration"
          max_tokens: 50
        status_code: 200
      register: apilama_pyllm_result
      
    - name: Verify APILama to PyLLM integration
      assert:
        that:
          - apilama_pyllm_result.status == 200
          - apilama_pyllm_result.json.completion is defined
        fail_msg: "APILama to PyLLM integration failed"
        success_msg: "APILama to PyLLM integration successful"
      
    - name: Test WebLama to APILama integration
      uri:
        url: "{{ weblama_url }}/api/execute"
        method: POST
        body_format: json
        body:
          code: "print('Testing WebLama to APILama integration')"
          language: "python"
        status_code: 200
      register: weblama_apilama_result
      ignore_errors: yes
      
    - name: Verify WebLama to APILama integration
      assert:
        that:
          - weblama_apilama_result.status == 200
          - weblama_apilama_result.json.output is defined
          - "'Testing WebLama to APILama integration' in weblama_apilama_result.json.output"
        fail_msg: "WebLama to APILama integration failed"
        success_msg: "WebLama to APILama integration successful"
      ignore_errors: yes
      
    - name: Save integration test results
      copy:
        content: |
          {
            "apilama_pybox": {{ apilama_pybox_result | to_json }},
            "apilama_pyllm": {{ apilama_pyllm_result | to_json }},
            "weblama_apilama": {{ weblama_apilama_result | to_json }}
          }
        dest: "{{ test_output_dir }}/integration_test_results.json"
      
    - name: Display integration test summary
      debug:
        msg: "Integration tests completed"
