---
# PyBox component tests

- name: PyBox Tests
  hosts: local
  gather_facts: no
  vars:
    pybox_url: "{{ lookup('env', 'PYBOX_URL') | default('http://localhost:8001', true) }}"
    test_output_dir: "{{ playbook_dir }}/../test-reports"
  
  tasks:
    - name: Test PyBox code execution
      uri:
        url: "{{ pybox_url }}/api/execute"
        method: POST
        body_format: json
        body:
          code: "print('Hello from PyBox!')"
          language: "python"
        status_code: 200
      register: pybox_execute_result
      
    - name: Verify PyBox execution result
      assert:
        that:
          - pybox_execute_result.status == 200
          - pybox_execute_result.json.output is defined
          - "'Hello from PyBox!' in pybox_execute_result.json.output"
        fail_msg: "PyBox code execution failed"
        success_msg: "PyBox code execution successful"
      
    - name: Test PyBox history endpoint
      uri:
        url: "{{ pybox_url }}/api/history"
        method: GET
        status_code: 200
      register: pybox_history_result
      
    - name: Verify PyBox history result
      assert:
        that:
          - pybox_history_result.status == 200
          - pybox_history_result.json is defined
        fail_msg: "PyBox history retrieval failed"
        success_msg: "PyBox history retrieval successful"
      
    - name: Save PyBox test results
      copy:
        content: "{{ pybox_execute_result | to_nice_json }}"
        dest: "{{ test_output_dir }}/pybox_test_results.json"
      
    - name: Display PyBox test summary
      debug:
        msg: "PyBox tests completed successfully"
