---
# BEXY component tests

- name: BEXY Tests
  hosts: local
  gather_facts: no
  vars:
    bexy_url: "{{ lookup('env', 'BEXY_URL') | default('http://localhost:8001', true) }}"
    test_output_dir: "{{ playbook_dir }}/../test-reports"
  
  tasks:
    - name: Test BEXY code execution
      uri:
        url: "{{ bexy_url }}/api/execute"
        method: POST
        body_format: json
        body:
          code: "print('Hello from BEXY!')"
          language: "python"
        status_code: 200
      register: bexy_execute_result
      
    - name: Verify BEXY execution result
      assert:
        that:
          - bexy_execute_result.status == 200
          - bexy_execute_result.json.output is defined
          - "'Hello from BEXY!' in bexy_execute_result.json.output"
        fail_msg: "BEXY code execution failed"
        success_msg: "BEXY code execution successful"
      
    - name: Test BEXY history endpoint
      uri:
        url: "{{ bexy_url }}/api/history"
        method: GET
        status_code: 200
      register: bexy_history_result
      
    - name: Verify BEXY history result
      assert:
        that:
          - bexy_history_result.status == 200
          - bexy_history_result.json is defined
        fail_msg: "BEXY history retrieval failed"
        success_msg: "BEXY history retrieval successful"
      
    - name: Save BEXY test results
      copy:
        content: "{{ bexy_execute_result | to_nice_json }}"
        dest: "{{ test_output_dir }}/bexy_test_results.json"
      
    - name: Display BEXY test summary
      debug:
        msg: "BEXY tests completed successfully"
