---
# PyLLM component tests

- name: PyLLM Tests
  hosts: local
  gather_facts: no
  vars:
    getllm_url: "{{ lookup('env', 'GETLLM_URL') | default('http://localhost:8002', true) }}"
    test_output_dir: "{{ playbook_dir }}/../test-reports"
  
  tasks:
    - name: Test PyLLM completion endpoint
      uri:
        url: "{{ getllm_url }}/api/complete"
        method: POST
        body_format: json
        body:
          prompt: "Hello, world!"
          max_tokens: 50
        status_code: 200
      register: getllm_complete_result
      
    - name: Verify PyLLM completion result
      assert:
        that:
          - getllm_complete_result.status == 200
          - getllm_complete_result.json.completion is defined
        fail_msg: "PyLLM completion failed"
        success_msg: "PyLLM completion successful"
      
    - name: Test PyLLM models endpoint
      uri:
        url: "{{ getllm_url }}/api/models"
        method: GET
        status_code: 200
      register: getllm_models_result
      
    - name: Verify PyLLM models result
      assert:
        that:
          - getllm_models_result.status == 200
          - getllm_models_result.json is defined
        fail_msg: "PyLLM models retrieval failed"
        success_msg: "PyLLM models retrieval successful"
      
    - name: Save PyLLM test results
      copy:
        content: "{{ getllm_complete_result | to_nice_json }}"
        dest: "{{ test_output_dir }}/getllm_test_results.json"
      
    - name: Display PyLLM test summary
      debug:
        msg: "PyLLM tests completed successfully"
